version: '3.8'

services:
  ib-gateway:
    restart: always
    platform: linux/amd64  # IB Gateway requires amd64
    build:
      context: ./latest
    image: ghcr.io/gnzsnz/ib-gateway:latest
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "7"
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-paper}
      TWS_USERID_PAPER: ${TWS_USERID_PAPER:-}
      TWS_PASSWORD_PAPER: ${TWS_PASSWORD_PAPER:-}
      TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
      TWS_ACCEPT_INCOMING: ${TWS_ACCEPT_INCOMING:-manual}
      READ_ONLY_API: ${READ_ONLY_API:-}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      BYPASS_WARNING: ${BYPASS_WARNING:-}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      TWS_COLD_RESTART: ${TWS_COLD_RESTART:-}
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      TWOFA_DEVICE: ${TWOFA_DEVICE:-}
      EXISTING_SESSION_DETECTED_ACTION: ${EXISTING_SESSION_DETECTED_ACTION:-primary}
      ALLOW_BLIND_TRADING: ${ALLOW_BLIND_TRADING:-no}
      TIME_ZONE: ${TIME_ZONE:-Africa/Johannesburg}
      TZ: ${TIME_ZONE:-Africa/Johannesburg}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      SSH_TUNNEL: ${SSH_TUNNEL:-}
      SSH_OPTIONS: ${SSH_OPTIONS:-}
      SSH_ALIVE_INTERVAL: ${SSH_ALIVE_INTERVAL:-}
      SSH_ALIVE_COUNT: ${SSH_ALIVE_COUNT:-}
      SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
      SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-}
      SSH_USER_TUNNEL: ${SSH_USER_TUNNEL:-}
      SSH_RESTART: ${SSH_RESTART:-}
      SSH_VNC_PORT: ${SSH_VNC_PORT:-}
    #    volumes:
    #      - ${PWD}/jts.ini:/home/ibgateway/Jts/jts.ini
    #      - ${PWD}/config.ini:/home/ibgateway/ibc/config.ini
    #      - ${PWD}/tws_settings/:${TWS_SETTINGS_PATH:-/home/ibgateway/Jts}
    #      - ${PWD}/ssh/:/home/ibgateway/.ssh
    ports:
      - "4001:4003"
      - "4002:4004"
      - "5900:5900"

  trading-app:
    platform: linux/amd64  # Maintain consistency with ib-gateway
    image: python:3.9
    depends_on:
      - ib-gateway
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "7"
    environment:
      IB_HOST: ib-gateway
      IB_PORT: 4004  # Using paper trading port
      DATABASE_URL: ${DATABASE_URL}
      VALR_API_KEY: ${VALR_API_KEY}
      VALR_API_SECRET: ${VALR_API_SECRET}
    volumes:
      - ./trading-app:/app
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt &&
              python collector.py"
